version : '3'

services:
  mysql:
    image: mysql:5.6
    container_name: dev_mysql
    command: --key_buffer_size=384M --sort_buffer_size=4M
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: default_schema
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80